project:
  type: website
  output-dir: _site

website:
  title: "HE REN"
  site-url: https://imrenhe.github.io
  description: "Personal website of He Ren"
  favicon: images/acorn.svg
  navbar:
    logo: images/acorn.svg
    title: HE REN
    right:
      - href: index.qmd
        text: HOME
      - href: teaching.qmd
        text: TEACHING
      - href: research.qmd
        text: RESEARCH
      - href: blog/index.qmd
        text: BLOG
      - href: photography.qmd
        text: PHOTOGRAPHY
  page-footer:
    left: "© 2026 He Ren. All rights reserved. Made with [Quarto](https://quarto.org)."
    right:
      - icon: github
        href: https://github.com/imrenhe
      - icon: linkedin
        href: https://www.linkedin.com/in/imrenhe/
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=POuWIfYAAAAJ&hl=en
     
format:
  html:
    theme:
      light: [cosmo, styles/light.scss]
      dark: [cosmo, styles/dark.scss]
    css: styles/styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Petrona:wght@400;500;700&family=Red+Hat+Text:wght@400;500;700&family=B612+Mono&display=swap" rel="stylesheet">
